spring:
  application:
    name: flow

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flow
    username: root
    password: 1234

    hikari:
      maximum-pool-size: 5